# Generated by Django 3.0.5 on 2020-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
            ],
        ),
    ]
