# Generated by Django 3.0.5 on 2020-04-29 08:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200429_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
