# Generated by Django 3.0.5 on 2020-04-29 11:30

from django.db import migrations, models
import django.utils.timezone
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_portfolio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='uploads/testimonial')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=django.utils.timezone.now, upload_to='uploads/portfolio'),
            preserve_default=False,
        ),
    ]
