# Generated by Django 3.0.5 on 2020-04-30 06:44

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200429_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypreferences',
            name='portal_contact_home_about',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
