# Generated by Django 3.0.5 on 2020-04-30 10:07

from django.db import migrations
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_mypreferences_portal_contact_home_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=django.utils.timezone.now, upload_to='blog'),
            preserve_default=False,
        ),
    ]
